version: '3.8'

services:
  saint-api:
    image: saint-api
    container_name: saint-api
    hostname: saint-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - AUTH_STRATEGY=${AUTH_STRATEGY}
      - AUTH0_ISSUER=${AUTH0_ISSUER}
      - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
      - API_KEYS=${API_KEYS}
      - AWS_CLIENT_ID=${AWS_CLIENT_ID}
      - AWS_CLIENT_SECRET=${AWS_CLIENT_SECRET}
      - AWS_DYNAMO_ENDPOINT=${AWS_DYNAMO_ENDPOINT}
      - AWS_DYNAMO_SAINT_TABLE_NAME=${AWS_DYNAMO_PERMISSION_TABLE_NAME}
      - AWS_REGION=${AWS_REGION}
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - 3009:80
    platform: linux/amd64
    restart: always

networks:
  default:
    external: true
    name: local-network