app:
  auth:
    strategy: ${AUTH_STRATEGY}
    auth0:
      issuer: ${AUTH0_ISSUER}
      apiAudience: ${AUTH0_API_AUDIENCE}
    apikeys: ${API_KEYS}
server:
  port: 80
#spring:
#  data:
#    mongodb:
#      uri: ${MONGODB_URI}
mongodb:
  uri: ${MONGODB_URI}
  saintDBName: ${MONGODB_SAINT_DB_NAME}
  replicaSet: ${MONGODB_REPLICA_SET}